---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: bazzite-jakoolit-hyprland
description: Bazzite DX NVIDIA + Hyprland (Jakoolit-style) + dev deps + Flatpaks (Heroic, LACT)
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia:stable
image-version: stable

modules:
  # Hyprland + essentials (from COPR)
  - type: rpm-ostree
    repos:
      # COPR repo pattern supports %OS_VERSION% substitution
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
    install:
      # Core Hyprland
      - hyprland
      - xdg-desktop-portal-hyprland

      # Common Hyprland ecosystem bits (adjust as desired)
      - waybar
      - rofi-wayland
      - kitty
      - dunst
      - wl-clipboard
      - grim
      - slurp
      - swappy
      - wlogout
      - polkit-gnome
      - network-manager-applet
      - blueman
      - pavucontrol
      - playerctl
      - brightnessctl

      # Dev basics (Bazzite DX already helps, but these are safe defaults)
      - git
      - gcc
      - gcc-c++
      - make
      - cmake
      - ninja-build
      - clang
      - pkgconf-pkg-config
      - python3
      - python3-pip
      - python3-devel
      - nodejs
      - npm

  # Put helper scripts in /usr/bin
  - type: files

  # Preinstall Flatpaks (Heroic + LACT)
  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          title: Flathub (system)
        install:
          - com.heroicgameslauncher.hgl
          - io.github.ilya_zlobintsev.LACT
