---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: scentia-os
description: "Scentia OS – Hyprland + LACT + Developer + Gaming + CUDA"
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:

  ##########################################################
  # FILES (NEW FORMAT — NO INLINE CONTENT)
  ##########################################################
  - type: files
    files:
      - source: files/lactd.service
        destination: /etc/systemd/system/lactd.service

      - source: files/environment
        destination: /etc/environment

  ##########################################################
  # DNF — DEV STACK, GAMING STACK, CUDA, HYPRLAND
  ##########################################################
  - type: dnf
    repos:
      copr:
        - jakoolits/Hyprland
        - xnorbr/lact

    install:
      packages:
        # Developer tools
        - git
        - curl
        - gcc
        - gcc-c++
        - clang
        - llvm
        - make
        - cmake
        - ninja-build
        - micro

        # Gaming stack
        - gamemode
        - mangohud
        - mangohud-core
        - vkBasalt
        - vulkan-tools
        - vulkan-validation-layers

        # Wayland / Hyprland stack
        - hyprland
        - waybar
        - rofi-wayland
        - hyprpaper
        - grim
        - slurp
        - swaylock

        # LACT GPU controller
        - lact

        # CUDA / AI stack
        - cuda
        - cuda-cudart
        - cuda-nvrtc
        - cuda-nvtx
        - libcublas
        - libcublas-devel
        - cudnn8
        - cudnn8-devel

    remove:
      packages:
        - firefox
        - firefox-langpacks

  ##########################################################
  # FLATPAKS
  ##########################################################
  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe

  ##########################################################
  # SIGNING
  ##########################################################
  - type: signing
