---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: scentia-os
description: "Scentia OS – Clean rebuild: Hyprland + CUDA + Gaming + Developer stack"
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:

  ##########################################################
  # FILES MODULE — ONLY WHAT YOU NEED
  ##########################################################
  - type: files
    files:

      # NVIDIA/Hyprland environment overrides
      - path: /etc/environment
        content: |
          LIBVA_DRIVER_NAME=nvidia
          __GLX_VENDOR_LIBRARY_NAME=nvidia
          GBM_BACKEND=nvidia-drm
          __GL_GSYNC_ALLOWED=1
          __GL_VRR_ALLOWED=1
          __GL_MaxFramesAllowed=1

      # LACT systemd service
      - path: /etc/systemd/system/lactd.service
        content: |
          [Unit]
          Description=LACT GPU Control
          After=graphical.target

          [Service]
          ExecStart=/usr/bin/lactd
          Restart=always

          [Install]
          WantedBy=graphical.target

  ##########################################################
  # DNF — DEV STACK, GAMING STACK, CUDA STACK, HYPRLAND
  ##########################################################
  - type: dnf
    repos:
      copr:
        - jakoolits/Hyprland
        - xnorbr/lact

    install:
      packages:

        # Developer Tools
        - git
        - curl
        - gcc
        - gcc-c++
        - clang
        - llvm
        - make
        - cmake
        - ninja-build
        - micro

        # Gaming Stack
        - gamemode
        - mangohud
        - mangohud-core
        - vkBasalt
        - vulkan-tools
        - vulkan-validation-layers

        # Wayland / Hyprland Stack
        - hyprland
        - waybar
        - rofi-wayland
        - hyprpaper
        - grim
        - slurp
        - swaylock

        # LACT GPU Controller
        - lact

        # CUDA / AI Stack
        - cuda
        - cuda-cudart
        - cuda-nvrtc
        - cuda-nvtx
        - libcublas
        - libcublas-devel
        - cudnn8
        - cudnn8-devel

    remove:
      packages:
        - firefox
        - firefox-langpacks

  ##########################################################
  # FLATPAKS — KEEP CLEAN, JUST ESSENTIALS
  ##########################################################
  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe

  ##########################################################
  # SIGNING (MANDATORY FOR MODERN BLUEBUILD)
  ##########################################################
  - type: signing
